persistence true
persistence_location /mosquitto/data/

# Logs
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true

# Listener principal MQTT (puerto 1883)
listener 1883 0.0.0.0
allow_anonymous true
